config/routes.rb
Rails.application.routes.draw do
  get 'projects/index'
  get 'teams/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :apps
  resources :buildpacks
  resources :plugins
  resources :projects
  resources :teams
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/app.rb
# frozen_string_literal: true

class App < ApplicationRecord
  enum deploy_type: { buildpack: 'buildpack', docker: 'docker' }
  before_create :generate_uuid

  validates :name, presence: true

  def generate_uuid
    self.uuid = SecureRandom.uuid
  end
end

app/models/app_buildpack.rb
# frozen_string_literal: true

class AppBuildpack < ApplicationRecord
  belongs_to :app
  belongs_to :buildpack
end

app/models/app_deploy.rb
# frozen_string_literal: true

class AppDeploy < ApplicationRecord
  belongs_to :app
  belongs_to :deploy
end

app/models/app_plugin.rb
# frozen_string_literal: true

class AppPlugin < ApplicationRecord
  belongs_to :app
  belongs_to :plugin
end

app/models/app_variable.rb
# frozen_string_literal: true

class AppVariable < ApplicationRecord
  belongs_to :app

  validates :name, presence: true
  validates :value, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.human_enum_name(enum_name, enum_value)
    I18n.t("activerecord.enums.#{model_name.i18n_key}.#{enum_name.to_s.pluralize}.#{enum_value}")
  end

  def self.enum_options_for_select(enum_name)
    I18n.t("activerecord.enums.#{model_name.i18n_key}.#{enum_name.to_s.pluralize}").map do |key, value|
      [value, key]
    end
  end
end

app/models/buildpack.rb
# frozen_string_literal: true

class Buildpack < ApplicationRecord
  validates :name, presence: true
  validates :url, presence: true
end

app/models/deploy.rb
# frozen_string_literal: true

class Deploy < ApplicationRecord
  belongs_to :app_deploy
end

app/models/plugin.rb
# frozen_string_literal: true

class Plugin < ApplicationRecord
  enum service_type: { postgres: 'postgres', redis: 'redis', elasticsearch: 'elasticsearch',
                       letsencrypt: 'letsencrypt', rabbitmq: 'rabbitmq' }

  validates :name, presence: true
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  validates :name, presence: true
end

app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
  validates :name, presence: true
end

app/models/team_project.rb
# frozen_string_literal: true

class TeamProject < ApplicationRecord
  belongs_to :team
  belongs_to :project
end

app/models/team_user.rb
# frozen_string_literal: true

class TeamUser < ApplicationRecord
  belongs_to :team
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :user_app_activities, dependent: :nullify
  has_many :team_users, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    "#{name} #{surname}"
  end

  def name_initials
    "#{name[0]}#{surname[0]}"
  end
end

app/models/user_app_activity.rb
# frozen_string_literal: true

class UserAppActivity < ApplicationRecord
  belongs_to :user
  belongs_to :app

  validates :action, presence: true

  enum action: { add: 'add', change: 'change', exclude: 'exclude' }
end

app/controllers/apps_controller.rb
# frozen_string_literal: true

class AppsController < ApplicationController
  before_action :list_apps, only: %i[index]
  before_action :set_app, only: %i[show edit update destroy]

  def index; end

  def show; end

  def new; end

  def edit; end

  def update
    if @app.update(app_params)
      redirect_to apps_path, notice: t('apps.updated')
    else
      render :edit
    end
  end

  def destroy; end

  private

  def set_app
    @app = App.find(params[:id])
  end

  def app_params
    params.require(:app).permit(:name, :description, :deploy_type)
  end

  def list_apps
    @apps = App.all
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/controllers/projects_controller.rb
# frozen_string_literal: true

class ProjectsController < ApplicationController
  before_action :set_project, only: %i[edit update]
  before_action :list_projects, only: %i[index new edit]

  def index; end

  def new; end

  def edit; end

  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to projects_path, notice: t('projects.created')
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to projects_path, notice: t('projects.updated')
    else
      render :edit
    end
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name)
  end

  def list_projects
    @projects = Project.all
  end
end

app/controllers/teams_controller.rb
# frozen_string_literal: true

class TeamsController < ApplicationController
  before_action :set_team, only: %i[edit update]
  before_action :list_teams, only: %i[index new edit]

  def index; end

  def new; end

  def edit; end

  def create
    @team = Team.new(team_params)
    if @team.save
      redirect_to teams_path, notice: t('teams.created')
    else
      render :new
    end
  end

  def update
    if @team.update(team_params)
      redirect_to teams_path, notice: t('teams.updated')
    else
      render :edit
    end
  end

  private

  def set_team
    @team = Team.find(params[:id])
  end

  def team_params
    params.require(:team).permit(:name)
  end

  def list_teams
    @teams = Team.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/helpers/teams_helper.rb
# frozen_string_literal: true

module TeamsHelper
end

app/views/projects/edit.html.erb
<div class='container-md mx-auto dark:text-white bg-gray-100 dark:bg-gray-800 rounded-lg p-4 w-full md:w-2/3 lg:w-2/5'>
  <div class="mb-8">
    <%= form_with(model: @project, url: project_path(@project.id), method: :put, html: { class: 'max-w-sm mx-auto' }) do |form| %>
      <div>
        <%= form.label :name, class: 'label' %>
        <%= form.text_field :name, class: 'input-text', required: true %>
      </div>
      <div class="flex mt-8 justify-between gap-8">
        <%= link_to projects_path, class: 'btn-secondary' do %>
          Cancel
        <% end %>
        <%= form.submit 'Save', class: 'btn-primary w-auto' %>
      </div>
    <% end %>
  </div>
</div>

app/views/projects/index.html.erb
<div class='container-md mx-auto dark:text-white bg-gray-100 dark:bg-gray-800 rounded-lg p-4 w-full md:w-2/3 lg:w-2/5'>
  <div class="flex rounded p-2 mb-2 flex-row-reverse">
    <%= link_to new_project_path, class: "btn flex align-middle text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16"> <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/> </svg>
      <span class="flex align-middle p-[2px]">New</span>
    <% end %>
  </div>
  <div class="divide-y divide-gray-100">
    <% @projects.each do |project| %>
      <%= link_to edit_project_path(project.id), class: "flex p-4 bg-gray-700 cursor-pointer rounded" do %>
        <div class='w-full flex justify-between'>
          <div>
            <p class="text-sm font-medium text-gray-900 dark:text-gray-100">
              <%= project.name %>
            </p>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/projects/new.html.erb
<div class='container-md mx-auto bg-gray-100 dark:bg-gray-800 rounded-lg p-4 w-full md:w-2/3 lg:w-2/5'>
  <%= form_with(model: Project.new, url: projects_path, method: :post, html: { class: 'max-w-sm mx-auto' }) do |form| %>
    <div class="mb-8">
      <%= form.label :name, class: 'label' %>
      <%= form.text_field :name, class: 'input-text', required: true %>
    </div>
    <div class="flex mt-8 justify-between gap-8">
      <%= link_to projects_path, class: 'btn-secondary' do %>
        Cancel
      <% end %>
      <%= form.submit 'Save', class: 'btn-primary w-auto' %>
    </div>
  <% end %>
</div>