config/routes.rb
Rails.application.routes.draw do
  get 'projects/index'
  get 'teams/index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :apps
  resources :buildpacks
  resources :plugins
  resources :projects
  resources :teams
  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/app.rb
# frozen_string_literal: true

class App < ApplicationRecord
  enum deploy_type: { buildpack: 'buildpack', docker: 'docker' }
  before_create :generate_uuid

  validates :name, presence: true

  def generate_uuid
    self.uuid = SecureRandom.uuid
  end
end

app/models/app_buildpack.rb
# frozen_string_literal: true

class AppBuildpack < ApplicationRecord
  belongs_to :app
  belongs_to :buildpack
end

app/models/app_deploy.rb
# frozen_string_literal: true

class AppDeploy < ApplicationRecord
  belongs_to :app
  belongs_to :deploy
end

app/models/app_plugin.rb
# frozen_string_literal: true

class AppPlugin < ApplicationRecord
  belongs_to :app
  belongs_to :plugin
end

app/models/app_variable.rb
# frozen_string_literal: true

class AppVariable < ApplicationRecord
  belongs_to :app

  validates :name, presence: true
  validates :value, presence: true
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class

  def self.human_enum_name(enum_name, enum_value)
    I18n.t("activerecord.enums.#{model_name.i18n_key}.#{enum_name.to_s.pluralize}.#{enum_value}")
  end

  def self.enum_options_for_select(enum_name)
    I18n.t("activerecord.enums.#{model_name.i18n_key}.#{enum_name.to_s.pluralize}").map do |key, value|
      [value, key]
    end
  end
end

app/models/buildpack.rb
# frozen_string_literal: true

class Buildpack < ApplicationRecord
  validates :name, presence: true
  validates :url, presence: true
end

app/models/deploy.rb
# frozen_string_literal: true

class Deploy < ApplicationRecord
  belongs_to :app_deploy
end

app/models/plugin.rb
# frozen_string_literal: true

class Plugin < ApplicationRecord
  enum service_type: { postgres: 'postgres', redis: 'redis', elasticsearch: 'elasticsearch',
                       letsencrypt: 'letsencrypt', rabbitmq: 'rabbitmq' }

  validates :name, presence: true
end

app/models/project.rb
# frozen_string_literal: true

class Project < ApplicationRecord
  validates :name, presence: true
end

app/models/team.rb
# frozen_string_literal: true

class Team < ApplicationRecord
  validates :name, presence: true
end

app/models/team_project.rb
# frozen_string_literal: true

class TeamProject < ApplicationRecord
  belongs_to :team
  belongs_to :project
end

app/models/team_user.rb
# frozen_string_literal: true

class TeamUser < ApplicationRecord
  belongs_to :team
  belongs_to :user
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :user_app_activities, dependent: :nullify
  has_many :team_users, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def full_name
    "#{name} #{surname}"
  end

  def name_initials
    "#{name[0]}#{surname[0]}"
  end
end

app/models/user_app_activity.rb
# frozen_string_literal: true

class UserAppActivity < ApplicationRecord
  belongs_to :user
  belongs_to :app

  validates :action, presence: true

  enum action: { add: 'add', change: 'change', exclude: 'exclude' }
end

app/controllers/apps_controller.rb
# frozen_string_literal: true

class AppsController < ApplicationController
  before_action :list_apps, only: %i[index]
  before_action :set_app, only: %i[show edit update destroy]

  def index; end

  def show; end

  def new; end

  def edit; end

  def update
    if @app.update(app_params)
      redirect_to apps_path, notice: t('apps.updated')
    else
      render :edit
    end
  end

  def destroy; end

  private

  def set_app
    @app = App.find(params[:id])
  end

  def app_params
    params.require(:app).permit(:name, :description, :deploy_type)
  end

  def list_apps
    @apps = App.all
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/projects_helper.rb
# frozen_string_literal: true

module ProjectsHelper
end

app/helpers/teams_helper.rb
# frozen_string_literal: true

module TeamsHelper
end

app/views/apps/edit.html.erb
<div class='container-md mx-auto dark:text-white bg-gray-100 dark:bg-gray-800 rounded-lg p-4 w-full md:w-2/3 lg:w-2/5'>
  <div class="mb-8">
    <%= form_with(model: @app, url: app_path(@app.id), method: :put, html: { class: 'max-w-sm mx-auto' }) do |form| %>
      <div class="mb-5">
        <%= form.label :name, class: 'label' %>
        <%= form.text_field :name, class: 'input-text', required: true %>
      </div>
      <div class="mb-5">
        <%= form.label :description, class: 'label' %>
        <%= form.text_area :description, class: 'input-text', required: true %>
      </div>
      <div class="mb-5">
        <%= form.label :deploy_type, class: 'label' %>
        <%= form.select :deploy_type, options_for_select(App.enum_options_for_select("deploy_type"), selected: @app.deploy_type), {}, class: "select-tag" %>
      </div>
      <div class="flex mt-8 justify-between gap-8">
        <%= link_to apps_path, class: 'btn-secondary' do %>
          Cancel
        <% end %>
        <%= form.submit 'Save', class: 'btn-primary w-auto' %>
      </div>
    <% end %>
  </div>
</div>

app/views/apps/index.html.erb
<div class='container-md mx-auto bg-gray-100 dark:bg-gray-800 rounded-lg p-4 w-full md:w-2/3 lg:w-2/5'>
  <div class="flex rounded p-2 mb-2 flex-row-reverse">
    <%= link_to new_app_path, class: "btn flex align-middle text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-blue-600 dark:hover:bg-blue-700 focus:outline-none dark:focus:ring-blue-800" do %>
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16"> <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z"/> </svg>
      <span class="flex align-middle p-[2px]">New</span>
    <% end %>
  </div>
  <div class="divide-y divide-gray-100">
    <% @apps.each do |app| %>
      <%= link_to edit_app_path(app.id), class: "flex p-4 bg-gray-700 cursor-pointer rounded" do %>
        <div class='w-full flex justify-between'>
          <div>
            <p class="text-sm font-medium text-gray-900 dark:text-gray-100">
              <%= app.name %>
            </p>
            <p class="text-sm text-gray-500 dark:text-gray-300">
              <%= app.description %>
            </p>
          </div>
          <svg class="w-5 h-5 ms-2.5 rtl:rotate-[270deg]" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 18 18">
            <path stroke="white" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M15 11v4.833A1.166 1.166 0 0 1 13.833 17H2.167A1.167 1.167 0 0 1 1 15.833V4.167A1.166 1.166 0 0 1 2.167 3h4.618m4.447-2H17v5.768M9.111 8.889l7.778-7.778"/>
          </svg>
        </div>
      <% end %>
    <% end %>
  </ul>
</div>

app/views/apps/new.html.erb
<div class='container-md mx-auto dark:text-white bg-gray-100 dark:bg-gray-800 rounded-lg p-4 w-full md:w-2/3 lg:w-2/5'>
  <div class="mb-8" data-controller="app">
    <%= form_with(model: App.new, url: apps_path, method: :post, html: { class: 'mx-auto' }) do |form| %>
      <div class="mb-5">
        <%= form.label :name, class: 'label' %>
        <%= form.text_field :name, class: 'input-text', required: true %>
      </div>
      <div class="mb-5">
        <%= form.label :description, class: 'label' %>
        <%= form.text_area :description, class: 'input-text', required: true %>
      </div>
      <div class="mb-8">
        <%= form.label :deploy_type, class: 'label' %>
        <%= select_tag "deploy_type", options_for_select(App.enum_options_for_select("deploy_type")), include_blank: 'Chose an option', placeholder: 'Tipo de deploy', class: "select-tag" %>
      </div>
      
      <div id="buildpacks" class='hidden mb-5'>
        <hr class="mb-5 border-slate-400" />
        <div class="mb-5 flex justify-between gap-2">
          <div class="grow">
            <% buildpacks = Buildpack.all.map {|c| ["#{c.name}",c.id,]} %>
            <%= form.label :buildpack, value: 'Buildpacks', class: 'label' %>
            <%= select_tag "buildpack", options_for_select(buildpacks), include_blank: 'Chose an option', placeholder: 'Buildpack', class: "select-tag" %>
          </div>
          <div class="self-end">
            <div id="add-buildpack" class="btn-primary">Add</div>
          </div>
        </div>
      </div>
      <hr class="border-slate-400" />
      <div class="flex mt-10 justify-between gap-8">
        <%= link_to apps_path, class: 'btn-secondary' do %>
          Cancel
        <% end %>
        <%= form.submit 'Save', class: 'btn-primary w-auto' %>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en" class="dark">
  <head>
    <title>LaunchBox</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gray-50 dark:bg-gray-900">
    <% if current_user.present? %>
      <%= render "shared/navbar" %>
      <main class="container mx-auto mt-28 px-5 flex">
        <%= yield %>
      </main>
    <% else %>
      <main>
        <%= yield %>
      </main>
    <% end %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="bg-white dark:bg-gray-800 border-b border-gray-300 dark:border-gray-600">
  <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
    <div class="relative flex h-16 items-center justify-between">
      <div class="flex flex-1 items-center justify-center sm:items-stretch sm:justify-start">
        <div class="flex flex-shrink-0 items-center">
          <%= link_to root_path do %>
            <img class="h-8 w-auto" src="https://dokku.com/assets/dokku-logo.svg" alt="Your Company">
          <% end %>
        </div>
        <div class="hidden sm:ml-6 sm:block">
          <div class="flex space-x-4">
            <%= link_to "Apps", apps_path, class: "nav-button" %>
            <%= link_to "Teams", teams_path, class: "nav-button" %>
            <%= link_to "Projects", projects_path, class: "nav-button" %>
          </div>
        </div>
      </div>
      <div class="absolute inset-y-0 right-0 flex items-center pr-2 sm:static sm:inset-auto sm:ml-6 sm:pr-0">
        <button id="theme-toggle" type="button" class="mr-2 text-gray-500 dark:text-gray-400 hover:bg-gray-100 dark:hover:bg-gray-700 focus:outline-none focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 rounded-lg text-sm p-2.5">
          <svg id="theme-toggle-dark-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M17.293 13.293A8 8 0 016.707 2.707a8.001 8.001 0 1010.586 10.586z"></path></svg>
          <svg id="theme-toggle-light-icon" class="hidden w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M10 2a1 1 0 011 1v1a1 1 0 11-2 0V3a1 1 0 011-1zm4 8a4 4 0 11-8 0 4 4 0 018 0zm-.464 4.95l.707.707a1 1 0 001.414-1.414l-.707-.707a1 1 0 00-1.414 1.414zm2.12-10.607a1 1 0 010 1.414l-.706.707a1 1 0 11-1.414-1.414l.707-.707a1 1 0 011.414 0zM17 11a1 1 0 100-2h-1a1 1 0 100 2h1zm-7 4a1 1 0 011 1v1a1 1 0 11-2 0v-1a1 1 0 011-1zM5.05 6.464A1 1 0 106.465 5.05l-.708-.707a1 1 0 00-1.414 1.414l.707.707zm1.414 8.486l-.707.707a1 1 0 01-1.414-1.414l.707-.707a1 1 0 011.414 1.414zM4 11a1 1 0 100-2H3a1 1 0 000 2h1z" fill-rule="evenodd" clip-rule="evenodd"></path></svg>
        </button>
        <button type="button" class="relative rounded-full dark:bg-gray-800 p-1 text-gray-400 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2 focus:ring-offset-gray-800">
          <span class="absolute -inset-1.5"></span>
          <span class="sr-only">View notifications</span>
          <svg class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M14.857 17.082a23.848 23.848 0 005.454-1.31A8.967 8.967 0 0118 9.75v-.7V9A6 6 0 006 9v.75a8.967 8.967 0 01-2.312 6.022c1.733.64 3.56 1.085 5.455 1.31m5.714 0a24.255 24.255 0 01-5.714 0m5.714 0a3 3 0 11-5.714 0" />
          </svg>
        </button>

        <div class="relative ml-3">
          <button type="button" class="flex mr-3 text-sm bg-gray-800 rounded-full md:mr-0 focus:ring-4 focus:ring-gray-300 dark:focus:ring-gray-600" id="user-menu-button" aria-expanded="false" data-dropdown-toggle="user-dropdown" data-dropdown-placement="bottom">
            <span class="sr-only">Open user menu</span>
            <% if current_user.avatar.blank? %>
              <%= image_tag('person', class: 'h-8 w-8 rounded-full') %>
            <% else %>
              <%= image_tag(current_user.avatar, class: 'h-8 w-8 rounded-full') %>
            <% end %>
          </button>
          <!-- Dropdown menu -->
          <div class="z-50 hidden my-4 text-base list-none bg-white divide-y divide-gray-100 rounded-lg shadow dark:bg-gray-700 dark:divide-gray-600" id="user-dropdown">
            <div class="px-4 py-3">
              <span class="block text-sm text-gray-900 dark:text-white"><%= current_user.name %></span>
              <span class="block text-sm  text-gray-500 truncate dark:text-gray-400"><%= current_user.email %></span>
            </div>
            <ul class="py-2" aria-labelledby="user-menu-button">
              <li>
                <a href="#" class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Settings</a>
              </li>
              <li>
                <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: 'text-left block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white w-full'  %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/shared/_user_info.html.erb
<div class="flex items-center gap-4">
  <div class="relative inline-flex items-center justify-center w-10 h-10 overflow-hidden bg-gray-100 rounded-full dark:bg-gray-600">
    <span class="font-medium text-gray-600 dark:text-gray-300"><%= user.name_initials %></span>
  </div>
  <div class="font-medium dark:text-white">
    <div><%= user.full_name %></div>
    <div class="text-sm text-gray-500 dark:text-gray-400">Joined in <%= user.created_at.strftime('%d/%m/%Y') %></div>
  </div>
</div>